colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["courses", "data_projects", "post"]

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  cardView = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = true
  showReadingTime = true
  showRelatedContent = false
  showTaxonomies = true
  sharingLinks = ["linkedin", "twitter", "email"]

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  groupByYear = false

[sitemap]
  excludedKinds = []
